### ISSUE TITLE
feature request: apply file name to all files

### ISSUE THREAD

**Issue by sarahcd** [movestore/write-shapefile#4]
Currently the user-provided file name is applied only to the folder containing the shapefile. Regardless of the name provided, all files of the shapefile are named "data". When opened in a GIS software, the resulting layer is by default also named "data" and must be renamed to keep track of what it is. Ideally the name could be applied to the components of the shapefile as well.

**Comment by andreakoelzsch** [comment]
This is fixed, all the shapefile-files now have the same name. Furthermore, the Movebank Vocab List is included in renaming the track attributes to 10 digits. Would be great if you would test this. Thanks!
