### ISSUE TITLE
error using data from Movebank Location

### ISSUE THREAD

**Issue by sarahcd** [movestore/write-shapefile#6]
I get this error using data from multiple studies that were added using 'Movebank Location' followed by 'move2_loc to moveStack'.

`Error in writeOGR(data.spdf, dsn = targetDirShapeFiles, layer = file.name, : Can't convert columns of class: list; column names: cptr.lctn,dply.n.lct,dply.ff.lc,mrtlty.lct,mn.lctn`

Will share a workflow!

**Comment by andreakoelzsch** [comment]
update to move2 should solve this issues
