### ISSUE TITLE
feature request: polyline file

### ISSUE THREAD

**Issue by sarahcd** [movestore/write-shapefile#7]
A user reported that she continues to use the shapefile [download](https://www.movebank.org/cms/movebank-content/access-data#download_data_in_movebank_format) from Movebank rather than MoveApps because it includes a shapefile for the trajectory lines. This would be great to add to the App.

* See downloads from Movebank for examples.
* A line should be made for each segment as defined in the workflow.
* The two shapefiles could always be provided, or there could be a setting to select one or both.
* Could add an extension to the end of the filenames "_lines" or "_points".

**Comment by andreakoelzsch** [comment]
done, even with points, lines and lines segments
